# Generated by Django 4.1 on 2024-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="controllerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage", models.FloatField(default=0)),
                ("VPUF", models.FloatField(default=0)),
                ("VPA", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="dataPlaneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoughput", models.IntegerField(default=0)),
                ("filterCount", models.IntegerField(default=0)),
                ("avgDelay", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="deviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixCount", models.IntegerField(default=0)),
                ("throughput", models.IntegerField(default=0)),
                ("filterCount", models.IntegerField(default=0)),
            ],
        ),
    ]
