# Generated by Django 4.1 on 2024-04-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllermodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dataplanemodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
