# Generated by Django 4.1 on 2024-04-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_controllermodel_id_alter_dataplanemodel_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataplanemodel",
            old_name="thoughput",
            new_name="throughput",
        ),
    ]
