# Generated by Django 4.2 on 2024-04-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0007_rename_thoughput_dataplanemodel_throughput"),
    ]

    operations = [
        migrations.CreateModel(
            name="RIB_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dstIP", models.CharField(max_length=17)),
                ("nextHop", models.CharField(max_length=15)),
                ("interfaceId", models.IntegerField()),
                (
                    "deviceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.devicemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FIB_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dstIP", models.CharField(max_length=17)),
                ("interfaceId", models.CharField(max_length=15)),
                (
                    "deviceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.devicemodel",
                    ),
                ),
            ],
        ),
    ]
