# Generated by Django 4.2 on 2024-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rib_model',
            name='controller_ip',
            field=models.CharField(default='192.168.0.1', max_length=15),
        ),
    ]
