# Generated by Django 4.2 on 2024-04-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fib_model",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rib_model",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
